baseURL: "https://janfb.github.io" 
title: Jan Boelts (Teusen)
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Software
          url: software/
          weight: 3
        - name: Talks
          url: talks/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "I am a machine learning researcher and open source developer with a
      background in computational neuroscience. I am passionate about making recent
      advances in machine learning research available to researchers and practitioners"
    author: Jan Boelts
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data","talks"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true 
          title: Jan Boelts (Teusen) 
          subtitle: "I'm a machine learning researcher and open source developer with a
          background in computational neuroscience. I specialize in probabilistic
          methods, particularly simulation-based inference (SBI), and develop tools like
          the [**sbi** Python package](https://sbi-dev.github.io/sbi). I am passionate
          about making cutting-edge ML research more accessible for practitioners from
          all domains through high-quality software tools and educational resources." 
          imageUrl: "profile-pic.png" 
          imageWidth: 160
          imageHeight: 160 
          imageTitle: Jan Boelts (Teusen) 
          buttons:
            - name: Papers
              url: papers/
            - name: Software
              url: software/
            - name: Talks
              url: talks/
            - name: Courses
              url: courses/
            - name: Blog
              url: https://transferlab.ai/authors/jan-teusen/

    socialIcons:
        - name: Email
          url: mailto:jan.boelts@mailbox.org
        - name: Google Scholar
          url: https://scholar.google.de/citations?user=wsE4N68AAAAJ&hl=en
        - name: GitHub
          url: https://github.com/janfb
        - name: Twitter
          url: https://x.com/janfiete

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jan Boelts (Teusen)"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2